### ISSUE TITLE
Android 13 Beta is not working in ws-scrcpy while scrcpy works

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#208]
Android 13 Beta is not working in ws-scrcpy while scrcpy working without any issue

**Comment by drauggres** [comment]
Works fine for me with emulator (`Android API 33`), both screen streaming and events injection.
Is there any errors in logcat?
<details>
  <summary>Screenshot</summary>
  
![Android13](https://user-images.githubusercontent.com/7796592/177521844-2089f2b3-4b5b-4cef-ba68-43a438c84ffe.png)  
</details>

**Comment by krishtoautomate** [comment]
the above is from logcat

**Comment by drauggres** [comment]
> the above is from logcat

I don't see anything useful in this output.
Does it not work for you with emulator too?

**Comment by krishtoautomate** [comment]
Didnt check in emulators. Only real devices

**Comment by drauggres** [comment]
> Possible to make scrcpy jar with ws with latest scrcpy?

[Source code](https://github.com/NetrisTV/scrcpy/commits/feature/websocket-server) is open. You can try to rebase my changes on upstream. I have no plans to do this anytime soon.

**Comment by krishtoautomate** [comment]
Any command to build as jar?

**Comment by SPrasadT** [comment]
Even I have the same problem, for pixel 4a, the stream is not working, can someone please help on this. thanks

**Comment by drauggres** [comment]
@krishtoautomate @SPrasadT 

Can you try this branch?
https://github.com/drauggres/ws-scrcpy/tree/feature/scrcpy_v1.24

I didn't spent too much time and some things could be broken ("set clipboard" for sure). But at least streaming and control work (with emulator, but current version also works).

Also it would help if you check `master` branch with emulator.
And moreover would be helpful if you confirm that original scrcpy works with your android-13-devices (and if you can chech since what version).

**Comment by krishtoautomate** [comment]
Working in below scrcpy version

scrcpy 1.23 <https://github.com/Genymobile/scrcpy>

Dependencies (compiled / linked):
 - SDL: 2.0.20 / 2.0.20
 - libavcodec: 59.18.100 / 59.18.100
 - libavformat: 59.16.100 / 59.16.100
 - libavutil: 57.17.100 / 57.17.100
 - libusb: - / 1.0.25

**Comment by SPrasadT** [comment]
@drauggres I tried with this https://github.com/drauggres/ws-scrcpy/tree/feature/scrcpy_v1.24 but no luck. 

And yes, the streaming and control for android emulator 13, 33 API work fine with scrcpy version 1.24 but the same thing does not work with ws-scrcpy.

I tried the ws-scrcpy master branch version on emulator android 13, but doesn't work. Please help.

**Comment by SPrasadT** [comment]
Also I found this on logcat while starting the ws-scrcpy

```
07-22 19:10:43.258 23073 23097 E AndroidRuntime: java.lang.AssertionError: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:38)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at com.genymobile.scrcpy.Device.getDisplayIds(Device.java:353)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at com.genymobile.scrcpy.WebSocketConnection.getInitialInfo(WebSocketConnection.java:120)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at com.genymobile.scrcpy.WSServer.onOpen(WSServer.java:78)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at org.java_websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:654)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:717)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:288)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:221)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2103)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:1724)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:36)
07-22 19:10:43.258 23073 23097 E AndroidRuntime: 	... 9 more
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: Uncaught exception in thread WebSocketWorker-12: {}
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: java.lang.AssertionError: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:38)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.Device.getDisplayIds(Device.java:353)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.WebSocketConnection.getInitialInfo(WebSocketConnection.java:120)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.WSServer.onOpen(WSServer.java:78)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at org.java_websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:654)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:717)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:288)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:221)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: Caused by: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at java.lang.Class.getMethod(Class.java:2103)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at java.lang.Class.getMethod(Class.java:1724)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:36)
07-22 19:10:43.261 23073 23097 E o.j.s.WebSocketServer: 	... 9 more
07-22 19:10:58.947   418   418 E android.hardware.power.stats@1.0-service-mock: Failed to getEnergyData
```
@drauggres

**Comment by drauggres** [comment]
Please try this:
https://github.com/drauggres/ws-scrcpy/tree/bug/android_13

It is possible that google hid/removed `getDisplayIds()` method. Original scrcpy does not call this method (unless you pass incorrect value in `--display` argument), but ws-scrcpy always gets `id`s for all displays and show them in `Configure stream` dialog.
I have added [workaround](https://github.com/drauggres/scrcpy/commit/ac7ffeb91c1202bcdd1863457e7164dfad0889fb): it will return only default display id and also print all available methods in log (so I will need to to check logcat again).

**Comment by SPrasadT** [comment]
@drauggres - Thank you!! it works! now on ws-scrcpy, I tested this on a emulator, now I test it out on the real device and let you know the feedback.

**Comment by krishtoautomate** [comment]
@drauggres still not working on real device

**Comment by drauggres** [comment]
@krishtoautomate 

Make sure that there is no other versions running (easiest way is to reboot the device).
Than check logcat:
- find process id (it should be visible in ws-scrcpy interface and also in output)
- run `adb logcat --pid PID`

**Comment by krishtoautomate** [comment]
`home@bqatautomation-2 ~ % adb -s 15141JEC201224 logcat --pid 1728
--------- beginning of crash
07-07 16:40:13.266  1728  1813 E AndroidRuntime: FATAL EXCEPTION: WebSocketWorker-11
07-07 16:40:13.266  1728  1813 E AndroidRuntime: PID: 1728
07-07 16:40:13.266  1728  1813 E AndroidRuntime: java.lang.AssertionError: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:38)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at com.genymobile.scrcpy.Device.getDisplayIds(Device.java:333)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at com.genymobile.scrcpy.WebSocketConnection.getInitialInfo(WebSocketConnection.java:121)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at com.genymobile.scrcpy.WSServer.onOpen(WSServer.java:78)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at org.java_websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:654)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:717)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:288)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:221)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2103)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:1724)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:36)
07-07 16:40:13.266  1728  1813 E AndroidRuntime: 	... 9 more`

**Comment by krishtoautomate** [comment]
` adb -s 15141JEC201224 logcat --pid 24977
--------- beginning of main
07-22 12:27:29.256 24977 24977 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
07-22 12:27:29.259 24977 24977 I AndroidRuntime: Using default boot image
07-22 12:27:29.259 24977 24977 I AndroidRuntime: Leaving lock profiling enabled
07-22 12:27:29.357 24977 24977 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
07-22 12:27:29.357 24977 24977 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
07-22 12:27:29.364 24977 24977 W ziparchive: Unable to open '/data/local/tmp/scrcpy-server.dm': No such file or directory
07-22 12:27:29.389 24977 24977 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
07-22 12:27:29.395 24977 24977 D TrafficStats: tagSocket(42) with statsTag=0xffffffff, statsUid=-1
--------- beginning of crash
07-22 12:27:41.944 24977 24996 E AndroidRuntime: FATAL EXCEPTION: WebSocketWorker-11
07-22 12:27:41.944 24977 24996 E AndroidRuntime: PID: 24977
07-22 12:27:41.944 24977 24996 E AndroidRuntime: java.lang.AssertionError: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:38)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at com.genymobile.scrcpy.Device.getDisplayIds(Device.java:333)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at com.genymobile.scrcpy.WebSocketConnection.getInitialInfo(WebSocketConnection.java:121)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at com.genymobile.scrcpy.WSServer.onOpen(WSServer.java:78)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at org.java_websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:654)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:717)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:288)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:221)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:2103)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at java.lang.Class.getMethod(Class.java:1724)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:36)
07-22 12:27:41.944 24977 24996 E AndroidRuntime: 	... 9 more
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: Uncaught exception in thread WebSocketWorker-11: {}
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: java.lang.AssertionError: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:38)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.Device.getDisplayIds(Device.java:333)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.WebSocketConnection.getInitialInfo(WebSocketConnection.java:121)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.WSServer.onOpen(WSServer.java:78)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at org.java_websocket.server.WebSocketServer.onWebsocketOpen(WebSocketServer.java:654)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at org.java_websocket.WebSocketImpl.open(WebSocketImpl.java:717)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:288)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:221)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: Caused by: java.lang.NoSuchMethodException: android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayIds []
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at java.lang.Class.getMethod(Class.java:2103)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at java.lang.Class.getMethod(Class.java:1724)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	at com.genymobile.scrcpy.wrappers.DisplayManager.getDisplayIds(DisplayManager.java:36)
07-22 12:27:41.945 24977 24996 E o.j.s.WebSocketServer: 	... 9 more`

**Comment by drauggres** [comment]
@krishtoautomate 

I am pretty sure that you run wrong version (not from https://github.com/drauggres/ws-scrcpy/tree/bug/android_13)

**Comment by drauggres** [comment]
@krishtoautomate FYI to write multiline code block you need to wrap it in three backticks (```).

**Comment by krishtoautomate** [comment]
fixed. working on real device.

thanks @drauggres

**Comment by drauggres** [comment]
@krishtoautomate @SPrasadT 

I still would like to see the logcat output. In your case it should print all methods available in `DisplayManager`.

https://github.com/NetrisTV/scrcpy/blob/ac7ffeb91c1202bcdd1863457e7164dfad0889fb/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayManager.java#L42-L47

**Comment by krishtoautomate** [comment]
`adb -s 15141JEC201224 logcat --pid 27746
--------- beginning of main
07-23 09:31:37.268 27746 27746 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
07-23 09:31:37.271 27746 27746 I AndroidRuntime: Using default boot image
07-23 09:31:37.271 27746 27746 I AndroidRuntime: Leaving lock profiling enabled
07-23 09:31:37.369 27746 27746 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
07-23 09:31:37.369 27746 27746 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
07-23 09:31:37.376 27746 27746 W ziparchive: Unable to open '/data/local/tmp/scrcpy-server.dm': No such file or directory
07-23 09:31:37.399 27746 27746 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
07-23 09:31:37.406 27746 27746 D TrafficStats: tagSocket(42) with statsTag=0xffffffff, statsUid=-1
07-23 09:31:37.408 27746 27746 D scrcpy  : Server started! /0.0.0.0:8886
07-23 09:31:58.133 27746 27764 D scrcpy  : Failed to get display ids
07-23 09:31:58.134 27746 27764 D scrcpy  : Available methods:
07-23 09:31:58.135 27746 27764 D scrcpy  : areUserDisabledHdrTypesAllowed
07-23 09:31:58.135 27746 27764 D scrcpy  : asBinder
07-23 09:31:58.135 27746 27764 D scrcpy  : connectWifiDisplay
07-23 09:31:58.136 27746 27764 D scrcpy  : createVirtualDisplay
07-23 09:31:58.136 27746 27764 D scrcpy  : disconnectWifiDisplay
07-23 09:31:58.136 27746 27764 D scrcpy  : equals
07-23 09:31:58.136 27746 27764 D scrcpy  : forgetWifiDisplay
07-23 09:31:58.136 27746 27764 D scrcpy  : getAmbientBrightnessStats
07-23 09:31:58.136 27746 27764 D scrcpy  : getBrightness
07-23 09:31:58.136 27746 27764 D scrcpy  : getBrightnessConfigurationForDisplay
07-23 09:31:58.136 27746 27764 D scrcpy  : getBrightnessConfigurationForUser
07-23 09:31:58.136 27746 27764 D scrcpy  : getBrightnessEvents
07-23 09:31:58.136 27746 27764 D scrcpy  : getBrightnessInfo
07-23 09:31:58.136 27746 27764 D scrcpy  : getClass
07-23 09:31:58.136 27746 27764 D scrcpy  : getDefaultBrightnessConfiguration
07-23 09:31:58.136 27746 27764 D scrcpy  : getDisplayDecorationSupport
07-23 09:31:58.136 27746 27764 D scrcpy  : getDisplayIds
07-23 09:31:58.136 27746 27764 D scrcpy  : getDisplayInfo
07-23 09:31:58.136 27746 27764 D scrcpy  : getInterfaceDescriptor
07-23 09:31:58.136 27746 27764 D scrcpy  : getMinimumBrightnessCurve
07-23 09:31:58.136 27746 27764 D scrcpy  : getPreferredWideGamutColorSpaceId
07-23 09:31:58.136 27746 27764 D scrcpy  : getRefreshRateSwitchingType
07-23 09:31:58.137 27746 27764 D scrcpy  : getStableDisplaySize
07-23 09:31:58.137 27746 27764 D scrcpy  : getSystemPreferredDisplayMode
07-23 09:31:58.137 27746 27764 D scrcpy  : getUserDisabledHdrTypes
07-23 09:31:58.137 27746 27764 D scrcpy  : getUserPreferredDisplayMode
07-23 09:31:58.137 27746 27764 D scrcpy  : getWifiDisplayStatus
07-23 09:31:58.137 27746 27764 D scrcpy  : hashCode
07-23 09:31:58.137 27746 27764 D scrcpy  : isMinimalPostProcessingRequested
07-23 09:31:58.137 27746 27764 D scrcpy  : isUidPresentOnDisplay
07-23 09:31:58.137 27746 27764 D scrcpy  : notify
07-23 09:31:58.137 27746 27764 D scrcpy  : notifyAll
07-23 09:31:58.137 27746 27764 D scrcpy  : pauseWifiDisplay
07-23 09:31:58.137 27746 27764 D scrcpy  : registerCallback
07-23 09:31:58.137 27746 27764 D scrcpy  : registerCallbackWithEventMask
07-23 09:31:58.137 27746 27764 D scrcpy  : releaseVirtualDisplay
07-23 09:31:58.138 27746 27764 D scrcpy  : renameWifiDisplay
07-23 09:31:58.138 27746 27764 D scrcpy  : requestColorMode
07-23 09:31:58.138 27746 27764 D scrcpy  : resizeVirtualDisplay
07-23 09:31:58.138 27746 27764 D scrcpy  : resumeWifiDisplay
07-23 09:31:58.138 27746 27764 D scrcpy  : setAreUserDisabledHdrTypesAllowed
07-23 09:31:58.138 27746 27764 D scrcpy  : setBrightness
07-23 09:31:58.138 27746 27764 D scrcpy  : setBrightnessConfigurationForDisplay
07-23 09:31:58.138 27746 27764 D scrcpy  : setBrightnessConfigurationForUser
07-23 09:31:58.138 27746 27764 D scrcpy  : setRefreshRateSwitchingType
07-23 09:31:58.138 27746 27764 D scrcpy  : setShouldAlwaysRespectAppRequestedMode
07-23 09:31:58.138 27746 27764 D scrcpy  : setTemporaryAutoBrightnessAdjustment
07-23 09:31:58.138 27746 27764 D scrcpy  : setTemporaryBrightness
07-23 09:31:58.138 27746 27764 D scrcpy  : setUserDisabledHdrTypes
07-23 09:31:58.138 27746 27764 D scrcpy  : setUserPreferredDisplayMode
07-23 09:31:58.138 27746 27764 D scrcpy  : setVirtualDisplayState
07-23 09:31:58.138 27746 27764 D scrcpy  : setVirtualDisplaySurface
07-23 09:31:58.138 27746 27764 D scrcpy  : shouldAlwaysRespectAppRequestedMode
07-23 09:31:58.138 27746 27764 D scrcpy  : startWifiDisplayScan
07-23 09:31:58.139 27746 27764 D scrcpy  : stopWifiDisplayScan
07-23 09:31:58.139 27746 27764 D scrcpy  : toString
07-23 09:31:58.139 27746 27764 D scrcpy  : wait
07-23 09:31:58.139 27746 27764 D scrcpy  : wait
07-23 09:31:58.139 27746 27764 D scrcpy  : wait
07-23 09:31:58.139 27746 27764 D scrcpy  : ///
07-23 09:31:58.172 27746 27764 D MtpDeviceJNI: register_android_mtp_MtpDevice
07-23 09:31:58.189 27746 27764 W VideoCapabilities: Unsupported mime image/vnd.android.heic
07-23 09:31:58.200 27746 27764 D scrcpy  : Client entered the room!
07-23 09:31:58.208 27746 27764 I scrcpy  : Device: Google Pixel 4a (Android 13)
07-23 09:31:58.230 27746 27764 D scrcpy  : Failed to get display ids
07-23 09:31:58.231 27746 27764 D scrcpy  : Available methods:
07-23 09:31:58.231 27746 27764 D scrcpy  : areUserDisabledHdrTypesAllowed
07-23 09:31:58.231 27746 27764 D scrcpy  : asBinder
07-23 09:31:58.231 27746 27764 D scrcpy  : connectWifiDisplay
07-23 09:31:58.231 27746 27764 D scrcpy  : createVirtualDisplay
07-23 09:31:58.231 27746 27764 D scrcpy  : disconnectWifiDisplay
07-23 09:31:58.232 27746 27764 D scrcpy  : equals
07-23 09:31:58.232 27746 27764 D scrcpy  : forgetWifiDisplay
07-23 09:31:58.232 27746 27764 D scrcpy  : getAmbientBrightnessStats
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightness
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightnessConfigurationForDisplay
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightnessConfigurationForUser
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightnessEvents
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightnessInfo
07-23 09:31:58.232 27746 27764 D scrcpy  : getClass
07-23 09:31:58.232 27746 27764 D scrcpy  : getDefaultBrightnessConfiguration
07-23 09:31:58.232 27746 27764 D scrcpy  : getDisplayDecorationSupport
07-23 09:31:58.232 27746 27764 D scrcpy  : getDisplayIds
07-23 09:31:58.232 27746 27764 D scrcpy  : getDisplayInfo
07-23 09:31:58.232 27746 27764 D scrcpy  : getInterfaceDescriptor
07-23 09:31:58.232 27746 27764 D scrcpy  : getMinimumBrightnessCurve
07-23 09:31:58.232 27746 27764 D scrcpy  : getPreferredWideGamutColorSpaceId
07-23 09:31:58.232 27746 27764 D scrcpy  : getRefreshRateSwitchingType
07-23 09:31:58.232 27746 27764 D scrcpy  : getStableDisplaySize
07-23 09:31:58.232 27746 27764 D scrcpy  : getSystemPreferredDisplayMode
07-23 09:31:58.233 27746 27764 D scrcpy  : getUserDisabledHdrTypes
07-23 09:31:58.233 27746 27764 D scrcpy  : getUserPreferredDisplayMode
07-23 09:31:58.233 27746 27764 D scrcpy  : getWifiDisplayStatus
07-23 09:31:58.233 27746 27764 D scrcpy  : hashCode
07-23 09:31:58.233 27746 27764 D scrcpy  : isMinimalPostProcessingRequested
07-23 09:31:58.233 27746 27764 D scrcpy  : isUidPresentOnDisplay
07-23 09:31:58.233 27746 27764 D scrcpy  : notify
07-23 09:31:58.233 27746 27764 D scrcpy  : notifyAll
07-23 09:31:58.233 27746 27764 D scrcpy  : pauseWifiDisplay
07-23 09:31:58.233 27746 27764 D scrcpy  : registerCallback
07-23 09:31:58.233 27746 27764 D scrcpy  : registerCallbackWithEventMask
07-23 09:31:58.233 27746 27764 D scrcpy  : releaseVirtualDisplay
07-23 09:31:58.233 27746 27764 D scrcpy  : renameWifiDisplay
07-23 09:31:58.233 27746 27764 D scrcpy  : requestColorMode
07-23 09:31:58.233 27746 27764 D scrcpy  : resizeVirtualDisplay
07-23 09:31:58.233 27746 27764 D scrcpy  : resumeWifiDisplay
07-23 09:31:58.233 27746 27764 D scrcpy  : setAreUserDisabledHdrTypesAllowed
07-23 09:31:58.233 27746 27764 D scrcpy  : setBrightness
07-23 09:31:58.234 27746 27764 D scrcpy  : setBrightnessConfigurationForDisplay
07-23 09:31:58.234 27746 27764 D scrcpy  : setBrightnessConfigurationForUser
07-23 09:31:58.234 27746 27764 D scrcpy  : setRefreshRateSwitchingType
07-23 09:31:58.234 27746 27764 D scrcpy  : setShouldAlwaysRespectAppRequestedMode
07-23 09:31:58.234 27746 27764 D scrcpy  : setTemporaryAutoBrightnessAdjustment
07-23 09:31:58.234 27746 27764 D scrcpy  : setTemporaryBrightness
07-23 09:31:58.234 27746 27764 D scrcpy  : setUserDisabledHdrTypes
07-23 09:31:58.234 27746 27764 D scrcpy  : setUserPreferredDisplayMode
07-23 09:31:58.234 27746 27764 D scrcpy  : setVirtualDisplayState
07-23 09:31:58.234 27746 27764 D scrcpy  : setVirtualDisplaySurface
07-23 09:31:58.234 27746 27764 D scrcpy  : shouldAlwaysRespectAppRequestedMode
07-23 09:31:58.234 27746 27764 D scrcpy  : startWifiDisplayScan
07-23 09:31:58.234 27746 27764 D scrcpy  : stopWifiDisplayScan
07-23 09:31:58.234 27746 27764 D scrcpy  : toString
07-23 09:31:58.234 27746 27764 D scrcpy  : wait
07-23 09:31:58.234 27746 27764 D scrcpy  : wait
07-23 09:31:58.234 27746 27764 D scrcpy  : wait
07-23 09:31:58.234 27746 27764 D scrcpy  : ///
07-23 09:31:58.242 27746 27764 D scrcpy  : First connection. Start new encoder.
07-23 09:31:58.246 27746 27794 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
07-23 09:31:58.246 27746 27794 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
07-23 09:31:58.249 27746 27796 D CCodec  : allocate(c2.qti.avc.encoder)
07-23 09:31:58.251 27746 27796 I Codec2Client: Available Codec2 services: "default" "software"
07-23 09:31:58.253 27746 27796 I CCodec  : setting up 'default' as default (vendor) store
07-23 09:31:58.262 27746 27796 I CCodec  : Created component [c2.qti.avc.encoder]
07-23 09:31:58.262 27746 27796 D CCodecConfig: read media type: video/avc
07-23 09:31:58.263 27746 27796 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
07-23 09:31:58.264 27746 27796 D ReflectedParamUpdater: ignored struct field coding.gop.values
07-23 09:31:58.270 27746 27796 D CCodecConfig: ignoring local param raw.color (0xc2001809) as it is already supported
07-23 09:31:58.271 27746 27796 I CCodecConfig: query failed after returning 21 values (BAD_INDEX)
07-23 09:31:58.271 27746 27796 D CCodecConfig: c2 config diff is Dict {
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 algo.bitrate-mode.value = 3
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 algo.complexity.value = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::i32 algo.priority.value = -1
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::float algo.rate.value = 30
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::i32 coded.average-qp.value = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coded.bitrate.value = 20000000
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::float coded.frame-rate.value = 30
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coded.picture-type.value = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coded.pl.level = 20480
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coded.pl.profile = 20480
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coded.vui.color.matrix = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coded.vui.color.primaries = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coded.vui.color.range = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coded.vui.color.transfer = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coding.intra-refresh.mode = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::float coding.intra-refresh.period = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 coding.request-sync-frame.value = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::i64 coding.sync-frame-interval.value = 1000000
07-23 09:31:58.271 27746 27796 D CCodecConfig:   Buffer coding.temporal-layering = {
07-23 09:31:58.271 27746 27796 D CCodecConfig:     00000000:  10 00 00 00 07 20 01 52  00 00 00 00 00 00 00 00  ..... .R........
07-23 09:31:58.271 27746 27796 D CCodecConfig:   }
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 default.color.matrix = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 default.color.primaries = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 default.color.range = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 default.color.transfer = 0
07-23 09:31:58.271 27746 27796 D CCodecConfig:   c2::u32 input.delay.value 
07-23 09:31:58.272 27746 27796 W ColorUtils: expected specified color aspects (0:0:0:0)
07-23 09:31:58.274 27746 27794 D scrcpy  : Using encoder: 'c2.qti.avc.encoder'
07-23 09:31:58.282 27746 27794 D CodecSeeding: Seed: codec c2.qti.avc.encoder, mediatype video/avc, overrideable 1
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-bpp,0)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-bpp-1080p,1.90)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-bpp-720p,2.25)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-bpp-540p,2.65)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-bpp-480p,3.00)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-bpp-320x240,0)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-qpmax,-1)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-qpmax-1080p,45)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-qpmax-720p,43)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-qpmax-540p,42)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-target-qpmax-480p,38)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-bitrate-phaseout,1.75)
07-23 09:31:58.282 27746 27794 D CodecProperties: setTuningValue(vq-boost-missing-qp,0.20)
07-23 09:31:58.282 27746 27794 D CodecProperties: setFeatureValue(_vq_eligible.device,1)
07-23 09:31:58.282 27746 27794 D CodecProperties: setFeatureValue(_quality.target,1)
07-23 09:31:58.282 27746 27794 D CodecSeeding: Seed: codec c2.qti.avc.encoder, mediatype video/avc, overrideable 0
07-23 09:31:58.282 27746 27794 D MediaCodec: shapeMediaFormat: deltas(1): AMessage(what = 0x00000000) = {
07-23 09:31:58.282 27746 27794 D MediaCodec:     int32_t android._encoding-quality-level = 0
07-23 09:31:58.282 27746 27794 D MediaCodec:   }
07-23 09:31:58.282 27746 27796 D CCodec  : [c2.qti.avc.encoder] buffers are bound to CCodec for this session
07-23 09:31:58.283 27746 27796 D CCodecConfig: no c2 equivalents for max-fps-to-encoder
07-23 09:31:58.283 27746 27796 D CCodecConfig: no c2 equivalents for color-format
07-23 09:31:58.283 27746 27796 D CCodecConfig: no c2 equivalents for repeat-previous-frame-after
07-23 09:31:58.283 27746 27796 D CCodecConfig: no c2 equivalents for flags
07-23 09:31:58.283 27746 27796 D CCodecConfig: no c2 equivalents for encoder
07-23 09:31:58.285 27746 27796 D CCodecConfig: c2 config diff is   c2::u32 coded.bitrate.value = 7340032
07-23 09:31:58.285 27746 27796 D CCodecConfig:   c2::float coded.frame-rate.value = 60
07-23 09:31:58.285 27746 27796 D CCodecConfig:   c2::i64 coding.sync-frame-interval.value = 10000000
07-23 09:31:58.285 27746 27796 D CCodecConfig:   c2::u32 raw.pixel-format.value = 34
07-23 09:31:58.285 27746 27796 D CCodecConfig:   c2::u32 raw.size.height = 720
07-23 09:31:58.285 27746 27796 D CCodecConfig:   c2::u32 raw.size.width = 320
07-23 09:31:58.285 27746 27796 W ColorUtils: expected specified color aspects (0:0:0:0)
07-23 09:31:58.286 27746 27796 W Codec2Client: query -- param skipped: index = 3254781982.
07-23 09:31:58.286 27746 27796 D CCodec  : encoding statistics level = 0
07-23 09:31:58.286 27746 27796 D CCodec  : setup formats input: AMessage(what = 0x00000000) = {
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t android._color-format = 2130708361
07-23 09:31:58.286 27746 27796 D CCodec  :   Rect crop(0, 0, 319, 719)
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t color-standard = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t color-range = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t color-transfer = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t frame-rate = 60
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t height = 720
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t intra-refresh-period = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   string mime = "video/raw"
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t prepend-sps-pps-to-idr-frames = 1
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t priority = 1
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t video-qp-average = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t width = 320
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t android._dataspace = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   int64_t android._C2MemoryUsage = 65536
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t color-format = 2130708361
07-23 09:31:58.286 27746 27796 D CCodec  : }
07-23 09:31:58.286 27746 27796 D CCodec  : setup formats output: AMessage(what = 0x00000000) = {
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t bitrate = 7340032
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t bitrate-mode = 1
07-23 09:31:58.286 27746 27796 D CCodec  :   Rect crop(0, 0, 319, 719)
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t width = 320
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t color-standard = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t color-range = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t color-transfer = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t frame-rate = 60
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t height = 720
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t intra-refresh-period = 0
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t level = 1
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t max-bitrate = 7340032
07-23 09:31:58.286 27746 27796 D CCodec  :   string mime = "video/avc"
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t prepend-sps-pps-to-idr-frames = 1
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t priority = 1
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t profile = 1
07-23 09:31:58.286 27746 27796 D CCodec  :   int32_t video-qp-average = 0
07-23 09:31:58.286 27746 27796 D CCodec  : }
07-23 09:31:58.287 27746 27796 I CCodecConfig: query failed after returning 21 values (BAD_INDEX)
07-23 09:31:58.288 27746 27796 D CCodec  : input format changed to AMessage(what = 0x00000000) = {
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t android._color-format = 2130708361
07-23 09:31:58.288 27746 27796 D CCodec  :   Rect crop(0, 0, 319, 719)
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t color-standard = 4
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t color-range = 2
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t color-transfer = 3
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t frame-rate = 60
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t height = 720
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t intra-refresh-period = 0
07-23 09:31:58.288 27746 27796 D CCodec  :   string mime = "video/raw"
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t prepend-sps-pps-to-idr-frames = 1
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t priority = 1
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t video-qp-average = 0
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t width = 320
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t android._dataspace = 259
07-23 09:31:58.288 27746 27796 D CCodec  :   int64_t android._C2MemoryUsage = 65536
07-23 09:31:58.288 27746 27796 D CCodec  :   int32_t color-format = 2130708361
07-23 09:31:58.288 27746 27796 D CCodec  : }
07-23 09:31:58.288 27746 27796 D GraphicBufferSource: setting dataspace: 0x103, acquired=0
07-23 09:31:58.288 27746 27796 D CCodec  : ISConfig minFps=10 => repeatDelayUs=100000 maxFps=60
07-23 09:31:58.307 27746 27796 W Codec2Client: query -- param skipped: index = 1342179345.
07-23 09:31:58.307 27746 27796 W Codec2Client: query -- param skipped: index = 2415921170.
07-23 09:31:58.307 27746 27796 W Codec2Client: query -- param skipped: index = 1610614798.
07-23 09:31:58.307 27746 27796 D CCodecBufferChannel: [c2.qti.avc.encoder#140] Query input allocators returned 0 params => BAD_INDEX (6)
07-23 09:31:58.307 27746 27796 D CCodecBufferChannel: [c2.qti.avc.encoder#140] Using basic input block pool with poolID 1 => got 1 - OK (0)
07-23 09:31:58.307 27746 27796 D CCodecBufferChannel: [c2.qti.avc.encoder#140] Query output allocators returned 0 params => BAD_INDEX (6)
07-23 09:31:58.308 27746 27796 I CCodecBufferChannel: [c2.qti.avc.encoder#140] Created output block pool with allocatorID 16 => poolID 28 - OK
07-23 09:31:58.308 27746 27796 D CCodecBufferChannel: [c2.qti.avc.encoder#140] Configured output block pool ids 28 => OK
07-23 09:31:58.322 27746 27792 D GraphicBufferSource: got buffer with new dataSpace #103
07-23 09:31:58.322 27746 27792 D C2OMXNode: dataspace changed to 0x103 pixel format: 0x1
07-23 09:31:58.325 27746 27792 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
07-23 09:31:58.325 27746 27792 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
07-23 09:31:58.355 27746 27800 D C2Store : Using ION
07-23 09:31:58.355 27746 27796 D CCodecConfig: c2 config diff is   Buffer coded.init-data.value = {
07-23 09:31:58.355 27746 27796 D CCodecConfig:     00000000:  00 00 00 01 67 42 80 0a  da 05 01 6e 80 6d 0a 13  ....gB.....n.m..
07-23 09:31:58.355 27746 27796 D CCodecConfig:     00000010:  50 00 00 00 01 68 ce 06  f2                       P....h...`

**Comment by krishtoautomate** [comment]
I see it

` Failed to get display ids
07-23 09:31:58.231 27746 27764 D scrcpy  : Available methods:
07-23 09:31:58.231 27746 27764 D scrcpy  : areUserDisabledHdrTypesAllowed
07-23 09:31:58.231 27746 27764 D scrcpy  : asBinder
07-23 09:31:58.231 27746 27764 D scrcpy  : connectWifiDisplay
07-23 09:31:58.231 27746 27764 D scrcpy  : createVirtualDisplay
07-23 09:31:58.231 27746 27764 D scrcpy  : disconnectWifiDisplay
07-23 09:31:58.232 27746 27764 D scrcpy  : equals
07-23 09:31:58.232 27746 27764 D scrcpy  : forgetWifiDisplay
07-23 09:31:58.232 27746 27764 D scrcpy  : getAmbientBrightnessStats
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightness
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightnessConfigurationForDisplay
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightnessConfigurationForUser
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightnessEvents
07-23 09:31:58.232 27746 27764 D scrcpy  : getBrightnessInfo`

**Comment by drauggres** [comment]
> 07-23 09:31:58.136 27746 27764 D scrcpy  : getDisplayIds

Interesting, the method is there, but app still throws `NoSuchMethodException`. Maybe google changed methods signature.

**Comment by drauggres** [comment]
@krishtoautomate can you run build and run https://github.com/drauggres/ws-scrcpy/tree/research/android_13_display_ids?
And share logcat here?

Server changes:
https://github.com/drauggres/scrcpy/blob/research/android_13_display_ids/server/src/main/java/com/genymobile/scrcpy/wrappers/DisplayManager.java#L46-L63

**Comment by krishtoautomate** [comment]
here is the logcat:

adb -s 15141JEC201224 logcat --pid 6186 
--------- beginning of main
07-23 15:28:51.277  6186  6186 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
07-23 15:28:51.281  6186  6186 I AndroidRuntime: Using default boot image
07-23 15:28:51.281  6186  6186 I AndroidRuntime: Leaving lock profiling enabled
07-23 15:28:51.374  6186  6186 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
07-23 15:28:51.374  6186  6186 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
07-23 15:28:51.380  6186  6186 W ziparchive: Unable to open '/data/local/tmp/scrcpy-server.dm': No such file or directory
07-23 15:28:51.409  6186  6186 D AndroidRuntime: Calling main entry com.genymobile.scrcpy.Server
07-23 15:28:51.416  6186  6186 D TrafficStats: tagSocket(42) with statsTag=0xffffffff, statsUid=-1
07-23 15:28:51.418  6186  6186 D scrcpy  : Server started! /0.0.0.0:8886
07-23 15:29:13.572  6186  6215 D scrcpy  : /// START ws-scrcpy/issues/208
07-23 15:29:13.573  6186  6215 D scrcpy  : Failed to get display ids
07-23 15:29:13.574  6186  6215 D scrcpy  : getDisplayIds parameters:
07-23 15:29:13.575  6186  6215 D scrcpy  : boolean
07-23 15:29:13.575  6186  6215 D scrcpy  : Return type: [I
07-23 15:29:13.575  6186  6215 D scrcpy  : /// END ws-scrcpy/issues/208
07-23 15:29:13.610  6186  6215 D MtpDeviceJNI: register_android_mtp_MtpDevice
07-23 15:29:13.626  6186  6215 W VideoCapabilities: Unsupported mime image/vnd.android.heic
07-23 15:29:13.639  6186  6215 D scrcpy  : Client entered the room!
07-23 15:29:13.648  6186  6215 I scrcpy  : Device: Google Pixel 4a (Android 13)
07-23 15:29:13.668  6186  6215 D scrcpy  : /// START ws-scrcpy/issues/208
07-23 15:29:13.668  6186  6215 D scrcpy  : Failed to get display ids
07-23 15:29:13.669  6186  6215 D scrcpy  : getDisplayIds parameters:
07-23 15:29:13.669  6186  6215 D scrcpy  : boolean
07-23 15:29:13.669  6186  6215 D scrcpy  : Return type: [I
07-23 15:29:13.669  6186  6215 D scrcpy  : /// END ws-scrcpy/issues/208
07-23 15:29:13.674  6186  6215 D scrcpy  : First connection. Start new encoder.
07-23 15:29:13.678  6186  6243 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
07-23 15:29:13.679  6186  6243 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
07-23 15:29:13.682  6186  6245 D CCodec  : allocate(c2.qti.avc.encoder)
07-23 15:29:13.684  6186  6245 I Codec2Client: Available Codec2 services: "default" "software"
07-23 15:29:13.686  6186  6245 I CCodec  : setting up 'default' as default (vendor) store
07-23 15:29:13.693  6186  6245 I CCodec  : Created component [c2.qti.avc.encoder]
07-23 15:29:13.694  6186  6245 D CCodecConfig: read media type: video/avc
07-23 15:29:13.697  6186  6245 D ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
07-23 15:29:13.698  6186  6245 D ReflectedParamUpdater: ignored struct field coding.gop.values
07-23 15:29:13.701  6186  6245 D CCodecConfig: ignoring local param raw.color (0xc2001809) as it is already supported
07-23 15:29:13.702  6186  6245 I CCodecConfig: query failed after returning 21 values (BAD_INDEX)
07-23 15:29:13.702  6186  6245 D CCodecConfig: c2 config diff is Dict {
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 algo.bitrate-mode.value = 3
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 algo.complexity.value = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::i32 algo.priority.value = -1
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::float algo.rate.value = 30
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::i32 coded.average-qp.value = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coded.bitrate.value = 20000000
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::float coded.frame-rate.value = 30
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coded.picture-type.value = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coded.pl.level = 20480
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coded.pl.profile = 20480
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coded.vui.color.matrix = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coded.vui.color.primaries = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coded.vui.color.range = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coded.vui.color.transfer = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coding.intra-refresh.mode = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::float coding.intra-refresh.period = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 coding.request-sync-frame.value = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::i64 coding.sync-frame-interval.value = 1000000
07-23 15:29:13.702  6186  6245 D CCodecConfig:   Buffer coding.temporal-layering = {
07-23 15:29:13.702  6186  6245 D CCodecConfig:     00000000:  10 00 00 00 07 20 01 52  00 00 00 00 00 00 00 00  ..... .R........
07-23 15:29:13.702  6186  6245 D CCodecConfig:   }
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 default.color.matrix = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 default.color.primaries = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 default.color.range = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 default.color.transfer = 0
07-23 15:29:13.702  6186  6245 D CCodecConfig:   c2::u32 input.delay.value 
07-23 15:29:13.703  6186  6245 W ColorUtils: expected specified color aspects (0:0:0:0)
07-23 15:29:13.705  6186  6243 D scrcpy  : Using encoder: 'c2.qti.avc.encoder'
07-23 15:29:13.715  6186  6243 D CodecSeeding: Seed: codec c2.qti.avc.encoder, mediatype video/avc, overrideable 1
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-bpp,0)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-bpp-1080p,1.90)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-bpp-720p,2.25)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-bpp-540p,2.65)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-bpp-480p,3.00)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-bpp-320x240,0)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-qpmax,-1)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-qpmax-1080p,45)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-qpmax-720p,43)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-qpmax-540p,42)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-target-qpmax-480p,38)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-bitrate-phaseout,1.75)
07-23 15:29:13.715  6186  6243 D CodecProperties: setTuningValue(vq-boost-missing-qp,0.20)
07-23 15:29:13.715  6186  6243 D CodecProperties: setFeatureValue(_vq_eligible.device,1)
07-23 15:29:13.715  6186  6243 D CodecProperties: setFeatureValue(_quality.target,1)
07-23 15:29:13.715  6186  6243 D CodecSeeding: Seed: codec c2.qti.avc.encoder, mediatype video/avc, overrideable 0
07-23 15:29:13.715  6186  6243 D MediaCodec: shapeMediaFormat: deltas(1): AMessage(what = 0x00000000) = {
07-23 15:29:13.715  6186  6243 D MediaCodec:     int32_t android._encoding-quality-level = 0
07-23 15:29:13.715  6186  6243 D MediaCodec:   }
07-23 15:29:13.716  6186  6245 D CCodec  : [c2.qti.avc.encoder] buffers are bound to CCodec for this session
07-23 15:29:13.716  6186  6245 D CCodecConfig: no c2 equivalents for max-fps-to-encoder
07-23 15:29:13.716  6186  6245 D CCodecConfig: no c2 equivalents for color-format
07-23 15:29:13.716  6186  6245 D CCodecConfig: no c2 equivalents for repeat-previous-frame-after
07-23 15:29:13.716  6186  6245 D CCodecConfig: no c2 equivalents for flags
07-23 15:29:13.716  6186  6245 D CCodecConfig: no c2 equivalents for encoder
07-23 15:29:13.718  6186  6245 D CCodecConfig: c2 config diff is   c2::u32 coded.bitrate.value = 7340032
07-23 15:29:13.718  6186  6245 D CCodecConfig:   c2::float coded.frame-rate.value = 60
07-23 15:29:13.718  6186  6245 D CCodecConfig:   c2::i64 coding.sync-frame-interval.value = 10000000
07-23 15:29:13.718  6186  6245 D CCodecConfig:   c2::u32 raw.pixel-format.value = 34
07-23 15:29:13.718  6186  6245 D CCodecConfig:   c2::u32 raw.size.height = 720
07-23 15:29:13.718  6186  6245 D CCodecConfig:   c2::u32 raw.size.width = 320
07-23 15:29:13.718  6186  6245 W ColorUtils: expected specified color aspects (0:0:0:0)
07-23 15:29:13.719  6186  6245 W Codec2Client: query -- param skipped: index = 3254781982.
07-23 15:29:13.719  6186  6245 D CCodec  : encoding statistics level = 0
07-23 15:29:13.719  6186  6245 D CCodec  : setup formats input: AMessage(what = 0x00000000) = {
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t android._color-format = 2130708361
07-23 15:29:13.719  6186  6245 D CCodec  :   Rect crop(0, 0, 319, 719)
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t color-standard = 0
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t color-range = 0
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t color-transfer = 0
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t frame-rate = 60
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t height = 720
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t intra-refresh-period = 0
07-23 15:29:13.719  6186  6245 D CCodec  :   string mime = "video/raw"
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t prepend-sps-pps-to-idr-frames = 1
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t priority = 1
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t video-qp-average = 0
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t width = 320
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t android._dataspace = 0
07-23 15:29:13.719  6186  6245 D CCodec  :   int64_t android._C2MemoryUsage = 65536
07-23 15:29:13.719  6186  6245 D CCodec  :   int32_t color-format = 2130708361
07-23 15:29:13.719  6186  6245 D CCodec  : }
07-23 15:29:13.720  6186  6245 D CCodec  : setup formats output: AMessage(what = 0x00000000) = {
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t bitrate = 7340032
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t bitrate-mode = 1
07-23 15:29:13.720  6186  6245 D CCodec  :   Rect crop(0, 0, 319, 719)
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t width = 320
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t color-standard = 0
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t color-range = 0
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t color-transfer = 0
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t frame-rate = 60
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t height = 720
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t intra-refresh-period = 0
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t level = 1
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t max-bitrate = 7340032
07-23 15:29:13.720  6186  6245 D CCodec  :   string mime = "video/avc"
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t prepend-sps-pps-to-idr-frames = 1
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t priority = 1
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t profile = 1
07-23 15:29:13.720  6186  6245 D CCodec  :   int32_t video-qp-average = 0
07-23 15:29:13.720  6186  6245 D CCodec  : }
07-23 15:29:13.720  6186  6245 I CCodecConfig: query failed after returning 21 values (BAD_INDEX)
07-23 15:29:13.722  6186  6245 D CCodec  : input format changed to AMessage(what = 0x00000000) = {
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t android._color-format = 2130708361
07-23 15:29:13.722  6186  6245 D CCodec  :   Rect crop(0, 0, 319, 719)
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t color-standard = 4
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t color-range = 2
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t color-transfer = 3
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t frame-rate = 60
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t height = 720
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t intra-refresh-period = 0
07-23 15:29:13.722  6186  6245 D CCodec  :   string mime = "video/raw"
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t prepend-sps-pps-to-idr-frames = 1
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t priority = 1
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t video-qp-average = 0
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t width = 320
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t android._dataspace = 259
07-23 15:29:13.722  6186  6245 D CCodec  :   int64_t android._C2MemoryUsage = 65536
07-23 15:29:13.722  6186  6245 D CCodec  :   int32_t color-format = 2130708361
07-23 15:29:13.722  6186  6245 D CCodec  : }
07-23 15:29:13.722  6186  6245 D GraphicBufferSource: setting dataspace: 0x103, acquired=0
07-23 15:29:13.722  6186  6245 D CCodec  : ISConfig minFps=10 => repeatDelayUs=100000 maxFps=60
07-23 15:29:13.751  6186  6245 W Codec2Client: query -- param skipped: index = 1342179345.
07-23 15:29:13.751  6186  6245 W Codec2Client: query -- param skipped: index = 2415921170.
07-23 15:29:13.751  6186  6245 W Codec2Client: query -- param skipped: index = 1610614798.
07-23 15:29:13.751  6186  6245 D CCodecBufferChannel: [c2.qti.avc.encoder#476] Query input allocators returned 0 params => BAD_INDEX (6)
07-23 15:29:13.751  6186  6245 D CCodecBufferChannel: [c2.qti.avc.encoder#476] Using basic input block pool with poolID 1 => got 1 - OK (0)
07-23 15:29:13.751  6186  6245 D CCodecBufferChannel: [c2.qti.avc.encoder#476] Query output allocators returned 0 params => BAD_INDEX (6)
07-23 15:29:13.753  6186  6245 I CCodecBufferChannel: [c2.qti.avc.encoder#476] Created output block pool with allocatorID 16 => poolID 29 - OK
07-23 15:29:13.753  6186  6245 D CCodecBufferChannel: [c2.qti.avc.encoder#476] Configured output block pool ids 29 => OK
07-23 15:29:13.783  6186  6241 D GraphicBufferSource: got buffer with new dataSpace #103
07-23 15:29:13.783  6186  6241 D C2OMXNode: dataspace changed to 0x103 pixel format: 0x1
07-23 15:29:13.786  6186  6241 W AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
07-23 15:29:13.786  6186  6241 W AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
07-23 15:29:13.820  6186  6249 D C2Store : Using ION
07-23 15:29:13.821  6186  6245 D CCodecConfig: c2 config diff is   Buffer coded.init-data.value = {
07-23 15:29:13.821  6186  6245 D CCodecConfig:     00000000:  00 00 00 01 67 42 80 0a  da 05 01 6e 80 6d 0a 13  ....gB.....n.m..
07-23 15:29:13.821  6186  6245 D CCodecConfig:     00000010:  50 00 00 00 01 68 ce 06  f2                       P....h...

**Comment by drauggres** [comment]
> 07-23 15:29:13.572 6186 6215 D scrcpy : /// START ws-scrcpy/issues/208
> 07-23 15:29:13.573 6186 6215 D scrcpy : Failed to get display ids
> 07-23 15:29:13.574 6186 6215 D scrcpy : getDisplayIds parameters:
> 07-23 15:29:13.575 6186 6215 D scrcpy : boolean
> 07-23 15:29:13.575 6186 6215 D scrcpy : Return type: [I
> 07-23 15:29:13.575 6186 6215 D scrcpy : /// END ws-scrcpy/issues/208

Yep. Google has added a boolean parameter, before Android 13 this method had no parameters.

**Comment by krishtoautomate** [comment]
@drauggres which tools or commands you use to build jar file?

**Comment by drauggres** [comment]
![image](https://user-images.githubusercontent.com/7796592/180620984-d3275af5-3642-4c38-b73c-f4e6a363ca09.png)

I use Android Studio: open `server` directory in it, then on the right side open `Gradle` panel, there `scrcpy:server [build]`

There is also `build_without_gradle.sh` script in `server` directory, it should work (but I didn't check).

**Comment by krishtoautomate** [comment]
gradle build worked but apk is created not jar file.

**Comment by drauggres** [comment]
> @drauggres gradle build worked but apk is created not jar file.

just rename it (both apk and jar are actually just a zip-archives)
